---
title: "LAB6"
author: "Harlee Ramos"
date: "2025-03-25"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
---


#6.5.1 Subset Selection Methods
```{r setup}
# Load Libraries
library(ISLR2)
```

```{r}
names(Hitters)
dim(Hitters)
sum(is.na(Hitters$Salary)) #The is.na() function can be used to identify the missing observations.
```

```{r}
Hitters <-na.omit(Hitters)
dim(Hitters)
sum(is.na(Hitters))
```

```{r setup_leaps}
# Load additional library
library(leaps)
```


```{r}
regfit.full<-regsubsets(Salary ~ ., Hitters)
summary(regfit.full)
```

```{r}
regfit.full<-regsubsets(Salary ~ ., Hitters,nvmax=19)
reg.summary<-summary(regfit.full)

```

```{r}
names(reg.summary)
```

```{r}
reg.summary$rsq<-summary(regfit.full)
```

```{r, fig.width=10, fig.height=10 }
par(mfrow = c(2, 2))
plot(reg.summary$rss, xlab = "Number of Variables", ylab = "RSS")
plot(reg.summary$adjr2, xlab = "Number of Variables", ylab = "Adjusted RSq")

```

```{r, fig.width=10, fig.height=10 }
which.max(reg.summary$adjr2)
plot(reg.summary$adjr2, xlab = "Number of Variables", ylab = "Adjusted RSq")
points(11, reg.summary$adjr2[11], col = "red", cex = 2, pch = 20)
```

```{r, fig.width=10, fig.height=5 }
which.max(reg.summary$adjr2)
plot(reg.summary$adjr2, xlab = "Number of Variables", ylab = "Adjusted RSq", type = "l")
points(11, reg.summary$adjr2[11], col = "red", cex = 2, pch = 20)
```




```{r, fig.width=10, fig.height=5 }
plot(reg.summary$cp, xlab = "Number of Variables", ylab = "Cp", type = "l")
which.min(reg.summary$cp)
points(10, reg.summary$cp[10], col = "red", cex = 2, pch = 20)
which.min(reg.summary$bic)
plot(reg.summary$bic, xlab = "Number of Variables", ylab = "BIC", type = "l")
points(6, reg.summary$bic[6], col = "red", cex = 2, pch = 20)
```

```{r, fig.width=10, fig.height=10 }
plot(regfit.full, scale = "r2")
plot(regfit.full, scale = "adjr2")
plot(regfit.full, scale = "Cp")
plot(regfit.full, scale = "bic")
```
```{r}
coef(regfit.full , 6)
```

```{r}
regfit.fwd <- regsubsets(Salary ~ ., data = Hitters, nvmax = 19, method = "forward")
summary(regfit.fwd)
regfit.bwd <- regsubsets(Salary ~ ., data = Hitters, nvmax = 19, method = "backward")
summary(regfit.bwd)
```
```{r}
coef(regfit.full, 7)
coef(regfit.fwd, 7)
coef(regfit.bwd, 7)
```

```{r}
set.seed (1)
train <- sample(c(TRUE , FALSE), nrow(Hitters),replace = TRUE)
test <- (! train)
```


```{r}
regfit.best <- regsubsets (Salary ~ ., data = Hitters[train , ], nvmax = 19)
```

```{r}
test.mat <- model.matrix(Salary ~ ., data = Hitters[test, ])
val.errors <- rep(NA, 19)
```

```{r}
for (i in 1:19) {
  coefi <- coef(regfit.best, id = i)
  pred <- test.mat[, names(coefi), drop = FALSE] %*% coefi
  val.errors[i] <- mean((Hitters[test, ]$Salary - as.vector(pred))^2)
}
```
```{r}
val.errors
```


```{r}
which.min(val.errors)
```



```{r}
coef(regfit.best , 7)
```

```{r}
predict.regsubsets <- function (object , newdata , id , ...) {
form <- as.formula(object$call [[2]])
mat <- model.matrix(form , newdata)
coefi <- coef(object , id = id)
xvars <- names(coefi)
mat[, xvars] %*% coefi
}
```

```{r}
regfit.best <- regsubsets(Salary ~ ., data = Hitters,nvmax=19)
coef(regfit.best,7)
```



```{r}
k <- 10  # for example, if using 10-fold cross-validation
set.seed(1)
folds <- sample(1:k, nrow(Hitters), replace = TRUE)
cv.errors <- matrix(NA, k, 19)
for (j in 1:k) {
  best.fit <- regsubsets(Salary ~ ., data = Hitters[folds != j, ], nvmax = 19)
  for (i in 1:19) {
    pred <- predict.regsubsets(best.fit, Hitters[folds == j, ], id = i)
    cv.errors[j, i] <- mean((Hitters$Salary[folds == j] - pred)^2)
  }
}
```

```{r}
mean.cv.errors <- apply(cv.errors , 2, mean)
mean.cv.errors
```

```{r}
reg.best <- regsubsets (Salary ~ ., data = Hitters ,nvmax = 19)
coef(reg.best , 10)

```

```{r}
# Create the model matrix and response vector from the same dataset
x <- model.matrix(Salary ~ ., data = Hitters)
y <- Hitters$Salary

```

```{r}
library(glmnet)
# Define the lambda grid
grid <- 10^seq(10, -2, length = 100)

# Fit the ridge regression model
ridge.mod <- glmnet(x, y, alpha = 0, lambda = grid)
```
```{r}
dim(coef(ridge.mod))
```

```{r}
ridge.mod$lambda [50]
coef(ridge.mod)[, 50]
```





















